
languageCode = "en"
languageName = "English"
contentDir = "content/en"
weight = 1
title = "metoraw"

[params]
displayName = "EN"
isoCode = "en"
rtl = false
dateFormat = "2 January 2006"
logo = ""
secondaryLogo = ""
# description = "My awesome website"
# copyright = "Copy, _right?_ :thinking_face:"

[params.author]
name = "metoraw"
email = "youremail@example.com"
image = "img/logo-comet-1.png"
imageQuality = 96
headline = ""
bio = "MetoRaw"
links = [{ github = "https://github.com/metoraw" }]
